iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_2: { p: 4000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000

  bspline_joint_trajectory_controller:
    type: joint_trajectory_controller/IBSplineJointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

    state_publish_rate: 1000

  bspline_ff_joint_trajectory_controller:
    type: feedforward_controllers/BSplineFFJointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      F_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      F_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    # True Inertia Centralized Version
    centralize: true
    parameters:
      F_joint_1: { b: 1.0, omega_c: 60.,  omega_o: 60.,  u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_2: { b: 1.0, omega_c: 60.,  omega_o: 60.,  u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_3: { b: 1.0, omega_c: 100., omega_o: 120., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_4: { b: 1.0, omega_c: 60.,  omega_o: 100., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_5: { b: 1.0, omega_c: 120., omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_6: { b: 1.0, omega_c: 75.,  omega_o: 100., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_7: { b: 1.0, omega_c: 120., omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }

  bspline_adrc_joint_trajectory_controller:
    type: adrc_controllers/BSplineADRCJointTrajectoryController
    state_publish_rate: 1000
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    # True Inertia Centralized Version
    centralize: false
    parameters:
      F_joint_1: { b: 1.0, omega_c: 60., omega_o: 60., u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_2: { b: 1.0, omega_c: 60.,  omega_o: 60., u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_3: { b: 1.0, omega_c: 100.,  omega_o: 120., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_4: { b: 1.0, omega_c: 60.,  omega_o: 100., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_5: { b: 1.0, omega_c: 120.,  omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_6: { b: 1.0, omega_c: 75.,  omega_o: 100., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      F_joint_7: { b: 1.0, omega_c: 120., omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }

iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_2: { p: 4000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      B_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      B_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      B_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      B_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000

  bspline_joint_trajectory_controller:
    type: joint_trajectory_controller/IBSplineJointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      B_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      B_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

    state_publish_rate: 1000

  bspline_ff_joint_trajectory_controller:
    type: feedforward_controllers/BSplineFFJointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 3000, i: 10.0, d: 50.0,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_2: { p: 3000, i: 50.0, d: 50.0, i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_3: { p: 1800,  i: 10.0, d: 10.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_4: { p: 1500, i: 10.0, d: 50.0, i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_5: { p: 1200,  i: 1.0, d: 10.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      B_joint_6: { p: 1000,  i: 1.0, d: 5.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      B_joint_7: { p: 1000,  i: 0.5, d: 3.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    # True Inertia Centralized Version
    centralize: true
    parameters:
      B_joint_1: { b: 1.0, omega_c: 50., omega_o: 60., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_2: { b: 1.0, omega_c: 60.,  omega_o: 60., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_3: { b: 1.0, omega_c: 100.,  omega_o: 150., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_4: { b: 1.0, omega_c: 60.,  omega_o: 200., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_5: { b: 1.0, omega_c: 100.,  omega_o: 120., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_6: { b: 1.0, omega_c: 75.,  omega_o: 100., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_7: { b: 1.0, omega_c: 150., omega_o: 150., u_max: 100000, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }

  bspline_adrc_joint_trajectory_controller:
    type: adrc_controllers/BSplineADRCJointTrajectoryController
    state_publish_rate: 1000
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    # True Inertia Centralized Version
    centralize: true
    parameters:
      B_joint_1: { b: 1.0, omega_c: 60., omega_o: 60., u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_2: { b: 1.0, omega_c: 60.,  omega_o: 60., u_max: 80, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_3: { b: 1.0, omega_c: 100.,  omega_o: 120., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_4: { b: 1.0, omega_c: 60.,  omega_o: 100., u_max: 40, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_5: { b: 1.0, omega_c: 120.,  omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_6: { b: 1.0, omega_c: 75.,  omega_o: 100., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
      B_joint_7: { b: 1.0, omega_c: 120., omega_o: 120., u_max: 20, u_stiction: 0., vs: 0.0, diag_offset: 0.0 }
