.build_template: &build_script
  stage: build
  image: osrf/ros:$ros_version-desktop-full-$ubuntu_version
  script:
    ## set up ros image
    - apt-get update && apt-get install -y cmake-curses-gui sudo
    - export TERM=xterm
    - cd ~
    - git config --global url."https://gitlab-ci-token:$CI_JOB_TOKEN@git.ias.informatik.tu-darmstadt.de/".insteadOf "git@git.ias.informatik.tu-darmstadt.de:"
    
    ## install ias ros scripts
    - git clone git@git.ias.informatik.tu-darmstadt.de:ias_ros/ias_ros_core.git ias_ros
    - cd ias_ros
    - printf $ros_version | ./install.sh
    - source setup.bash

    ## install packages
    - cd ~
    - "printf '%s\\n' \"- git: {local-name: src/$ias_package_name,
                                uri: '$CI_REPOSITORY_URL', 
                                version: $CI_COMMIT_REF_NAME}\" 
                                > ias_ros/rosinstall/optional/$ias_package_name.rosinstall"

    - ias install $ias_package_name
    - ias update
    - ias make
  tags:
    - docker


build_14.04:
  variables:
    ros_version: "indigo"
    ubuntu_version: "trusty"
    ias_package_name: "iiwas"
  <<: *build_script

build_16.04:
  variables:
    ros_version: "kinetic"
    ubuntu_version: "xenial"
    ias_package_name: "iiwas"
  <<: *build_script

trigger_ias_ros_core_build:
  stage: deploy
  script:
    - apt-get update && apt-get install -y curl
    - "curl -X POST 
            -F token=$IAS_ROS_CORE_TOKEN 
            -F ref=master
            -F \"variables[TRIGGERED_FROM]=$CI_PROJECT_PATH\"
            -F \"variables[TRIGGERED_BY]=$GITLAB_USER_EMAIL\"            
            https://git.ias.informatik.tu-darmstadt.de/api/v4/projects/229/trigger/pipeline"
  only:
    - master
  tags:
    - docker