iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true }
      F_joint_2: { p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true }
      F_joint_3: { p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      F_joint_4: { p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true }
      F_joint_5: { p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true }
      F_joint_6: { p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
      F_joint_7: { p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    # The stiffness and damping for impedance control is specified in
    # iiwas_driver/config/config.yaml. The stiffness/damping can not be tuned online.
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
      F_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
      F_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
      F_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      F_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
      F_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
      F_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    parameters:
      F_joint_1: { b: 1.5, omega_c: 55., k: 10, u_max: 320}
      F_joint_2: { b: 1.0, omega_c: 100., k: 20, u_max: 320}
      F_joint_3: { b: 6, omega_c: 50., k: 40, u_max: 176}
      F_joint_4: { b: 5, omega_c: 50., k: 40, u_max: 176}
      F_joint_5: { b: 18, omega_c: 35., k: 120, u_max: 110}
      F_joint_6: { b: 10, omega_c: 50., k: 20, u_max: 40}
      F_joint_7: { b: 20, omega_c: 25, k: 200, u_max: 40}


iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true }
      B_joint_2: { p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true }
      B_joint_3: { p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      B_joint_4: { p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true }
      B_joint_5: { p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true }
      B_joint_6: { p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
      B_joint_7: { p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    # The stiffness and damping for impedance control is specified in
    # iiwas_driver/config/config.yaml. The stiffness/damping can not be tuned online.
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
      B_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
      B_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
      B_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      B_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
      B_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
      B_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    parameters:
      B_joint_1: { b: 1.5, omega_c: 55., k: 10, u_max: 320}
      B_joint_2: { b: 1.0, omega_c: 100., k: 20, u_max: 320}
      B_joint_3: { b: 6, omega_c: 50., k: 40, u_max: 176}
      B_joint_4: { b: 5, omega_c: 50., k: 40, u_max: 176}
      B_joint_5: { b: 18, omega_c: 35., k: 120, u_max: 110}
      B_joint_6: { b: 10, omega_c: 50., k: 20, u_max: 40}
      B_joint_7: { b: 20, omega_c: 25, k: 200, u_max: 40}