iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - F_SFE
      - F_SAA
      - F_HR
      - F_EB
      - F_WR
      - F_WFE
      - F_WAA

  joint_impedance_controller:
    type: effort_controller/JointGroupPositionController
    joints:
      - F_SFE
      - F_SAA
      - F_HR
      - F_EB
      - F_WR
      - F_WFE
      - F_WAA

    F_SFE:
      pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_SAA:
      pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_HR:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_EB:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_WR:
      pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_WFE:
      pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}
    F_WAA:
      pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}


  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_SFE
      - F_SAA
      - F_HR
      - F_EB
      - F_WR
      - F_WFE
      - F_WAA


iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - B_SFE
      - B_SAA
      - B_HR
      - B_EB
      - B_WR
      - B_WFE
      - B_WAA

  joint_impedance_controller:
    type: effort_controller/JointGroupPositionController
    joints:
      - B_SFE
      - B_SAA
      - B_HR
      - B_EB
      - B_WR
      - B_WFE
      - B_WAA

    B_SFE:
      pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_SAA:
      pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_HR:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_EB:
      pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_WR:
      pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_WFE:
      pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}
    B_WAA:
      pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}


  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_SFE
      - B_SAA
      - B_HR
      - B_EB
      - B_WR
      - B_WFE
      - B_WAA