iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: {p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true}
      F_joint_2: {p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true}
      F_joint_3: {p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true}
      F_joint_4: {p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true}
      F_joint_5: {p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true}
      F_joint_6: {p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true}
      F_joint_7: {p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true}
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

#  gazebo_ros_control:
#    pid_gains:
#      F_joint_1: { p: 1000,  i: 0.0, d: 10,  i_clamp: 320, antiwindup: true } # Parameter for simulation
#      F_joint_2: { p: 2000, i: 0.0, d: 20,   i_clamp: 320, antiwindup: true } # Parameter for simulation
#      F_joint_3: { p: 500,  i: 0.0, d: 5.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
#      F_joint_4: { p: 800, i: 0.0, d: 20,   i_clamp: 176, antiwindup: true } # Parameter for simulation
#      F_joint_5: { p: 500,  i: 0.0, d: 3.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
#      F_joint_6: { p: 300,  i: 0.0, d: 4.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
#      F_joint_7: { p: 300,  i: 0.0, d: 1.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
#      F_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
#      F_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
#      F_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
#      F_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
#      F_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
#      F_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
#      F_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

      F_joint_1: { p: 1000,  i: 0.0, d: 10,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_2: { p: 2000, i: 0.0, d: 200,   i_clamp: 320, antiwindup: true } # Parameter for simulation
      F_joint_3: { p: 500,  i: 0.0, d: 5.0,  i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_4: { p: 800, i: 0.0, d: 20,   i_clamp: 176, antiwindup: true } # Parameter for simulation
      F_joint_5: { p: 500,  i: 0.0, d: 3.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      F_joint_6: { p: 300,  i: 0.0, d: 4.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      F_joint_7: { p: 300,  i: 0.0, d: 1.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000


iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: {p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true}
      B_joint_2: {p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true}
      B_joint_3: {p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true}
      B_joint_4: {p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true}
      B_joint_5: {p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true}
      B_joint_6: {p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true}
      B_joint_7: {p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true}
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

#  gazebo_ros_control:
#    pid_gains:
#      B_joint_1: { p: 1000, i: 0, d: 0.1,  i_clamp: 320, antiwindup: true }
#      B_joint_2: { p: 3500, i: 0, d: 10,   i_clamp: 320, antiwindup: true }
#      B_joint_3: { p: 500,  i: 0, d: 0.25, i_clamp: 176, antiwindup: true }
#      B_joint_4: { p: 1000, i: 0, d: 80,   i_clamp: 176, antiwindup: true }
#      B_joint_5: { p: 200,  i: 0, d: 3.0,  i_clamp: 110, antiwindup: true }
#      B_joint_6: { p: 400,  i: 0, d: 4.0,  i_clamp: 40,  antiwindup: true }
#      B_joint_7: { p: 250,  i: 0, d: 1.0,  i_clamp: 40,  antiwindup: true }

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
#      B_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
#      B_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
#      B_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
#      B_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
#      B_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
#      B_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
#      B_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

      B_joint_1: { p: 1000, i: 0, d: 0.1,  i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_2: { p: 3500, i: 0, d: 10,   i_clamp: 320, antiwindup: true } # Parameter for simulation
      B_joint_3: { p: 500,  i: 0, d: 0.25, i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_4: { p: 1000, i: 0, d: 80,   i_clamp: 176, antiwindup: true } # Parameter for simulation
      B_joint_5: { p: 200,  i: 0, d: 3.0,  i_clamp: 110, antiwindup: true } # Parameter for simulation
      B_joint_6: { p: 400,  i: 0, d: 4.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
      B_joint_7: { p: 250,  i: 0, d: 1.0,  i_clamp: 40,  antiwindup: true } # Parameter for simulation
    state_publish_rate: 1000
