iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true }
      F_joint_2: { p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true }
      F_joint_3: { p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      F_joint_4: { p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true }
      F_joint_5: { p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true }
      F_joint_6: { p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
      F_joint_7: { p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    # The stiffness and damping for impedance control is specified in
    # iiwas_driver/config/config.yaml. The stiffness/damping can not be tuned online.
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      F_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
      F_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
      F_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
      F_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      F_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
      F_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
      F_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    parameters:
      F_joint_1: { b: 1.0, omega_c: 50.,  omega_o: 50, u_max: 100000, u_stiction: 0., vs: 0.0 } # Parameter of Inertia Compatible
      F_joint_2: { b: 1.0, omega_c: 50.,  omega_o: 50, u_max: 100000, u_stiction: 0., vs: 0.0 }
      F_joint_3: { b: 1.0, omega_c: 50., omega_o: 50, u_max: 100000, u_stiction: 0., vs: 0.0 }
      F_joint_4: { b: 1.0, omega_c: 50., omega_o: 50, u_max: 100000, u_stiction: 0., vs: 0.0 }
      F_joint_5: { b: 1.0, omega_c: 50., omega_o: 50., u_max: 100000, u_stiction: 0., vs: 0.0 }
      F_joint_6: { b: 1.0, omega_c: 50., omega_o: 50., u_max: 100000, u_stiction: 0., vs: 0.0 }
      F_joint_7: { b: 1.0, omega_c: 100., omega_o: 100., u_max: 100000, u_stiction: 0., vs: 0.0 }

#      F_joint_1: { b: 0.25, omega_c: 30., omega_o: 75, u_max: 160, u_stiction: 0., vs: 0.01}
#      F_joint_2: { b: 0.2, omega_c: 30., omega_o: 75, u_max: 160, u_stiction: 0.0, vs: 0.05}
#      F_joint_3: { b: 1.1, omega_c: 50., omega_o: 75, u_max: 90, u_stiction: 0.2, vs: 0.05}
#      F_joint_4: { b: 1.0, omega_c: 50., omega_o: 150, u_max: 90, u_stiction: 0.5, vs: 0.05}
#      F_joint_5: { b: 3.0, omega_c: 50., omega_o: 180, u_max: 60, u_stiction: 0.5, vs: 0.05}
#      F_joint_6: { b: 5.0, omega_c: 50., omega_o: 180, u_max: 20, u_stiction: 0.6, vs: 0.05}
#      F_joint_7: { b: 6.0, omega_c: 50., omega_o: 200, u_max: 20, u_stiction: 0.4, vs: 0.05}


iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 2800.0, i: 80.0, d: 100.0, i_clamp: 320, antiwindup: true }
      B_joint_2: { p: 3500.0, i: 20.0, d: 80.0,  i_clamp: 320, antiwindup: true }
      B_joint_3: { p: 2800.0, i: 50.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      B_joint_4: { p: 1500.0, i: 10.0, d: 25.0,  i_clamp: 176, antiwindup: true }
      B_joint_5: { p: 1800.0, i: 10.0, d: 30.0,  i_clamp: 110, antiwindup: true }
      B_joint_6: { p: 1200.0, i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
      B_joint_7: { p: 800.0,  i: 15.0, d: 15.0,  i_clamp: 40,  antiwindup: true }
    state_publish_rate: 1000

  joint_position_impedance_trajectory_controller:
    # The stiffness and damping for impedance control is specified in
    # iiwas_driver/config/config.yaml. The stiffness/damping can not be tuned online.
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    state_publish_rate: 1000

  joint_feedforward_trajectory_controller:
    type: feedforward_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: { p: 2800.0, i: 10.0, d: 220.0, i_clamp: 320, antiwindup: true }
      B_joint_2: { p: 2500.0, i: 10.0, d: 120.0, i_clamp: 320, antiwindup: true }
      B_joint_3: { p: 2000.0, i: 10.0, d: 50.0,  i_clamp: 176, antiwindup: true }
      B_joint_4: { p: 1500.0, i: 10.0, d: 40.0,  i_clamp: 176, antiwindup: true }
      B_joint_5: { p: 1500.0, i: 0.0,  d: 15.0,  i_clamp: 110, antiwindup: true }
      B_joint_6: { p: 1200.0, i: 1.0,  d: 10.0,  i_clamp: 40,  antiwindup: true }
      B_joint_7: { p: 800.0,  i: 1.0,  d: 15.0,  i_clamp: 40,  antiwindup: true }

    state_publish_rate: 1000

  adrc_trajectory_controller:
    type: adrc_controllers/JointTrajectoryController
    state_publish_rate: 1000
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    parameters:
      B_joint_1: { b: 0.3, omega_c: 50., omega_o: 70, u_max: 90}
      B_joint_2: { b: 0.3, omega_c: 50., omega_o: 100, u_max: 90}
      B_joint_3: { b: 1.1, omega_c: 50., omega_o: 75, u_max: 50}
      B_joint_4: { b: 1.0, omega_c: 50., omega_o: 150, u_max: 50}
      B_joint_5: { b: 3.0, omega_c: 50., omega_o: 180, u_max: 40}
      B_joint_6: { b: 5.0, omega_c: 50., omega_o: 180, u_max: 20}
      B_joint_7: { b: 6.0, omega_c: 50., omega_o: 200, u_max: 20}