iiwa_front:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7
    gains:
      B_joint_1: {p: 800.0, i: 100.0, d: 80.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_2: {p: 800.0, i: 100.0, d: 100.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_3: {p: 300.0, i: 10.0, d: 25.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_4: {p: 300.0, i: 10.0, d: 25.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_5: {p: 200.0, i: 10.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_6: {p: 200.0, i: 10.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_7: {p: 100.0, i: 15.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}

  joint_position_impedance_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - F_joint_1
      - F_joint_2
      - F_joint_3
      - F_joint_4
      - F_joint_5
      - F_joint_6
      - F_joint_7


iiwa_back:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  # in Hz

  joint_position_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7

  joint_torque_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
    gains:
      B_joint_1: {p: 800.0, i: 100.0, d: 80.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_2: {p: 800.0, i: 100.0, d: 100.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_3: {p: 300.0, i: 10.0, d: 25.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_4: {p: 300.0, i: 10.0, d: 25.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_5: {p: 200.0, i: 10.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_6: {p: 200.0, i: 10.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}
      B_joint_7: {p: 100.0, i: 15.0, d: 5.0, i_clamp_min: -100, i_clamp_max: 100}

  joint_position_impedance_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - B_joint_1
      - B_joint_2
      - B_joint_3
      - B_joint_4
      - B_joint_5
      - B_joint_6
      - B_joint_7
