#include "iiwas_kinematics.h"
#include "math.h"
#include <iostream>

namespace iiwas_kinematics {

    Kinematics::Kinematics(const Vector3d &tcp_position, const Quaterniond &tcp_quaternion) : Kinematics() {
        tcp_pos_ = tcp_position;
        tcp_quat_ = tcp_quaternion;
        T_ee_.block<3, 1>(0, 3) = tcp_pos_;
        T_ee_.block<3, 3>(0, 0) = tcp_quat_.toRotationMatrix();
    }

    Kinematics::Kinematics() {
        d_bs_ = 0.36;     // Distance from base to shoulder
        d_se_ = 0.42;     // Distance from shoulder to elbow
        d_ew_ = 0.4;      // Distance from elbow to wrist
        d_wf_ = 0.151;    // Distance from elbow to finger(tip)

        dh_a_ << 0., 0., 0., 0., 0., 0., 0.;
        dh_alpha_ << -M_PI_2, M_PI_2, M_PI_2, -M_PI_2, -M_PI_2, M_PI_2, 0.;
        dh_d_ << d_bs_, 0., d_se_, 0., d_ew_, 0., d_wf_;

        pos_limits_lower << -170., -120., -170., -120., -170., -120., -175.;
        pos_limits_upper << 170., 120., 170., 120., 170., 120., 175.;
        vel_limits_lower << -85., -85., -100., -75., -130., -135., -135.;
        vel_limits_upper << 85., 85., 100., 75., 130., 135., 135.;
        pos_limits_lower = pos_limits_lower / 180. * M_PI;
        pos_limits_upper = pos_limits_upper / 180. * M_PI;
        vel_limits_lower = vel_limits_lower / 180. * M_PI;
        vel_limits_upper = vel_limits_upper / 180. * M_PI;

        T_ee_.setIdentity();
    }

    void Kinematics::transform_i(double q, int i, Kinematics::TransformMatrixType& T_i) {
        T_i << cos(q), -sin(q) * cos(dh_alpha_[i]), sin(q) * sin(dh_alpha_[i]), dh_a_[i] * cos(q),
                sin(q), cos(q) * cos(dh_alpha_[i]), -cos(q) * sin(dh_alpha_[i]), dh_a_[i] * sin(q),
                0., sin(dh_alpha_[i]), cos(dh_alpha_[i]), dh_d_[i],
                0., 0., 0., 1.;
    }

    void Kinematics::ForwardKinematics(const Kinematics::JointArrayType &q, Vector3d &out_ee_pos,
                                       Quaterniond &out_ee_quad) {
        T.setIdentity();
        for (int i = 0; i < NUM_OF_JOINTS; ++i) {
            transform_i(q[i], i, T_tmp);
            T = T * T_tmp;
        }
        T = T * T_ee_;
        out_ee_pos = T.block<3, 1>(0, 3);
        out_ee_quad = T.block<3, 3>(0, 0);
    }

    void Kinematics::Jacobian(const JointArrayType &q, JacobianType &out_jacobian) {
        JacobianPosType jac_pos;
        JacobianRotType jac_rot;
        JacobianPos(q, jac_pos);
        JacobianRot(q, jac_rot);
        out_jacobian.block<3, NUM_OF_JOINTS>(0, 0) = jac_pos;
        out_jacobian.block<3, NUM_OF_JOINTS>(3, 0) = jac_rot;
    }

    void Kinematics::JacobianPos(const Kinematics::JointArrayType &q, Kinematics::JacobianPosType &out_jacobian) {
        double q_1 = q[0];
        double q_2 = q[1];
        double q_3 = q[2];
        double q_4 = q[3];
        double q_5 = q[4];
        double q_6 = q[5];
        double q_7 = q[6];

        out_jacobian(0, 0) = d_ew_ * ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) - d_se_ * sin(q_1) * sin(q_2) + d_wf_ * ((((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * sin(q_5)) * sin(q_6) + (-(-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_6)) + tcp_pos_.x() * (((((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) + ((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6)) * cos(q_7) + ((-(-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-(((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) - ((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6)) * sin(q_7) + ((-(-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * ((((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * sin(q_5)) * sin(q_6) + (-(-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_6));
        out_jacobian(0, 1) = d_ew_ * (sin(q_2) * sin(q_4) * cos(q_1) * cos(q_3) + cos(q_1) * cos(q_2) * cos(q_4)) + d_se_ * cos(q_1) * cos(q_2) + d_wf_ * (((-sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_1) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5) * cos(q_1)) * sin(q_6) + (sin(q_2) * sin(q_4) * cos(q_1) * cos(q_3) + cos(q_1) * cos(q_2) * cos(q_4)) * cos(q_6)) + tcp_pos_.x() * ((((-sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_1) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5) * cos(q_1)) * cos(q_6) + (-sin(q_2) * sin(q_4) * cos(q_1) * cos(q_3) - cos(q_1) * cos(q_2) * cos(q_4)) * sin(q_6)) * cos(q_7) + ((sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_1) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_1) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-((-sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_1) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5) * cos(q_1)) * cos(q_6) - (-sin(q_2) * sin(q_4) * cos(q_1) * cos(q_3) - cos(q_1) * cos(q_2) * cos(q_4)) * sin(q_6)) * sin(q_7) + ((sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_1) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_1) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * (((-sin(q_2) * cos(q_1) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_1) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5) * cos(q_1)) * sin(q_6) + (sin(q_2) * sin(q_4) * cos(q_1) * cos(q_3) + cos(q_1) * cos(q_2) * cos(q_4)) * cos(q_6));
        out_jacobian(0, 2) = d_ew_ * (sin(q_1) * cos(q_3) + sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_4) + d_wf_ * (((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_4) * cos(q_5)) * sin(q_6) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_4) * cos(q_6)) + tcp_pos_.x() * ((((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_4) * cos(q_5)) * cos(q_6) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_4) * sin(q_6)) * cos(q_7) + ((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_5) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5) * cos(q_4)) * sin(q_7)) + tcp_pos_.y() * ((-((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_4) * cos(q_5)) * cos(q_6) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_4) * sin(q_6)) * sin(q_7) + ((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_5) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5) * cos(q_4)) * cos(q_7)) + tcp_pos_.z() * (((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_4) * cos(q_5)) * sin(q_6) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_4) * cos(q_6));
        out_jacobian(0, 3) = d_ew_ * ((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) + d_wf_ * ((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6) * cos(q_5) + (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_6)) + tcp_pos_.x() * (((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_5) * sin(q_7) + ((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_5) * cos(q_6) + ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_6)) * cos(q_7)) + tcp_pos_.y() * (((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_5) * cos(q_7) + (-(-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_5) * cos(q_6) - ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_6)) * sin(q_7)) + tcp_pos_.z() * ((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6) * cos(q_5) + (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_6));
        out_jacobian(0, 4) = d_wf_ * (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * sin(q_6) + tcp_pos_.x() * (((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * sin(q_7) + (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * cos(q_6) * cos(q_7)) + tcp_pos_.y() * (((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) - (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_7) - (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * sin(q_7) * cos(q_6)) + tcp_pos_.z() * (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * sin(q_6);
        out_jacobian(0, 5) = d_wf_ * ((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) - (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6)) + tcp_pos_.x() * (-(((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * sin(q_6) + ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_6)) * cos(q_7) + tcp_pos_.y() * ((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * sin(q_6) - ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_6)) * sin(q_7) + tcp_pos_.z() * ((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) - (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6));
        out_jacobian(0, 6) = tcp_pos_.x() * (-((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) + ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6)) * sin(q_7) + (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * cos(q_7)) + tcp_pos_.y() * ((-(((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) - ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6)) * cos(q_7) - (-((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * sin(q_7));

        out_jacobian(1, 0) = d_ew_ * ((sin(q_1) * sin(q_3) - cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) + d_se_ * sin(q_2) * cos(q_1) + d_wf_ * ((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * sin(q_6) + (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_6)) + tcp_pos_.x() * (((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) + ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6)) * cos(q_7) + ((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-(((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * cos(q_6) - ((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) - sin(q_2) * cos(q_1) * cos(q_4)) * sin(q_6)) * sin(q_7) + ((-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) - sin(q_2) * sin(q_4) * cos(q_1)) * sin(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * ((((-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * cos(q_4) + sin(q_2) * sin(q_4) * cos(q_1)) * cos(q_5) + (-sin(q_1) * cos(q_3) - sin(q_3) * cos(q_1) * cos(q_2)) * sin(q_5)) * sin(q_6) + (-(-sin(q_1) * sin(q_3) + cos(q_1) * cos(q_2) * cos(q_3)) * sin(q_4) + sin(q_2) * cos(q_1) * cos(q_4)) * cos(q_6));
        out_jacobian(1, 1) = d_ew_ * (sin(q_1) * sin(q_2) * sin(q_4) * cos(q_3) + sin(q_1) * cos(q_2) * cos(q_4)) + d_se_ * sin(q_1) * cos(q_2) + d_wf_ * (((-sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) + sin(q_1) * sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * sin(q_5)) * sin(q_6) + (sin(q_1) * sin(q_2) * sin(q_4) * cos(q_3) + sin(q_1) * cos(q_2) * cos(q_4)) * cos(q_6)) + tcp_pos_.x() * ((((-sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) + sin(q_1) * sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) + (-sin(q_1) * sin(q_2) * sin(q_4) * cos(q_3) - sin(q_1) * cos(q_2) * cos(q_4)) * sin(q_6)) * cos(q_7) + ((sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) - sin(q_1) * sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-((-sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) + sin(q_1) * sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) - (-sin(q_1) * sin(q_2) * sin(q_4) * cos(q_3) - sin(q_1) * cos(q_2) * cos(q_4)) * sin(q_6)) * sin(q_7) + ((sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) - sin(q_1) * sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * (((-sin(q_1) * sin(q_2) * cos(q_3) * cos(q_4) + sin(q_1) * sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_1) * sin(q_2) * sin(q_3) * sin(q_5)) * sin(q_6) + (sin(q_1) * sin(q_2) * sin(q_4) * cos(q_3) + sin(q_1) * cos(q_2) * cos(q_4)) * cos(q_6));
        out_jacobian(1, 2) = d_ew_ * (sin(q_1) * sin(q_3) * cos(q_2) - cos(q_1) * cos(q_3)) * sin(q_4) + d_wf_ * (((-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_4) * cos(q_5) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_5)) * sin(q_6) - (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_4) * cos(q_6)) + tcp_pos_.x() * ((((-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_4) * cos(q_5) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_5)) * cos(q_6) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_4) * sin(q_6)) * cos(q_7) + (-(-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5) * cos(q_4) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-((-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_4) * cos(q_5) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_5)) * cos(q_6) - (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_4) * sin(q_6)) * sin(q_7) + (-(-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5) * cos(q_4) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * (((-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_4) * cos(q_5) + (-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * sin(q_5)) * sin(q_6) - (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_4) * cos(q_6));
        out_jacobian(1, 3) = d_ew_ * ((-sin(q_1) * cos(q_2) * cos(q_3) - sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) + d_wf_ * ((-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6) * cos(q_5) + (-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_6)) + tcp_pos_.x() * (((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_5) * sin(q_7) + ((-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_5) * cos(q_6) + ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_6)) * cos(q_7)) + tcp_pos_.y() * (((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_5) * cos(q_7) + (-(-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_5) * cos(q_6) - ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_6)) * sin(q_7)) + tcp_pos_.z() * ((-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6) * cos(q_5) + (-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_6));
        out_jacobian(1, 4) = d_wf_ * (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * sin(q_6) + tcp_pos_.x() * (((-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) - (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * sin(q_7) + (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * cos(q_6) * cos(q_7)) + tcp_pos_.y() * (((-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) - sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) - (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_7) - (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * sin(q_7) * cos(q_6)) + tcp_pos_.z() * (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * sin(q_6);
        out_jacobian(1, 5) = d_wf_ * ((((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) - (-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6)) + tcp_pos_.x() * (-(((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * sin(q_6) + ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_6)) * cos(q_7) + tcp_pos_.y() * ((((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * sin(q_6) - ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * cos(q_6)) * sin(q_7) + tcp_pos_.z() * ((((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) - (-(sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) + sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6));
        out_jacobian(1, 6) = tcp_pos_.x() * (-((((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) + ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6)) * sin(q_7) + (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * cos(q_7)) + tcp_pos_.y() * ((-(((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * cos(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * sin(q_5)) * cos(q_6) - ((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * sin(q_4) - sin(q_1) * sin(q_2) * cos(q_4)) * sin(q_6)) * cos(q_7) - (-((sin(q_1) * cos(q_2) * cos(q_3) + sin(q_3) * cos(q_1)) * cos(q_4) + sin(q_1) * sin(q_2) * sin(q_4)) * sin(q_5) + (-sin(q_1) * sin(q_3) * cos(q_2) + cos(q_1) * cos(q_3)) * cos(q_5)) * sin(q_7));

        out_jacobian(2, 0) = 0;
        out_jacobian(2, 1) = d_ew_ * (-sin(q_2) * cos(q_4) + sin(q_4) * cos(q_2) * cos(q_3)) - d_se_ * sin(q_2) + d_wf_ * (((-sin(q_2) * sin(q_4) - cos(q_2) * cos(q_3) * cos(q_4)) * cos(q_5) + sin(q_3) * sin(q_5) * cos(q_2)) * sin(q_6) + (-sin(q_2) * cos(q_4) + sin(q_4) * cos(q_2) * cos(q_3)) * cos(q_6)) + tcp_pos_.x() * ((((-sin(q_2) * sin(q_4) - cos(q_2) * cos(q_3) * cos(q_4)) * cos(q_5) + sin(q_3) * sin(q_5) * cos(q_2)) * cos(q_6) + (sin(q_2) * cos(q_4) - sin(q_4) * cos(q_2) * cos(q_3)) * sin(q_6)) * cos(q_7) + ((sin(q_2) * sin(q_4) + cos(q_2) * cos(q_3) * cos(q_4)) * sin(q_5) + sin(q_3) * cos(q_2) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-((-sin(q_2) * sin(q_4) - cos(q_2) * cos(q_3) * cos(q_4)) * cos(q_5) + sin(q_3) * sin(q_5) * cos(q_2)) * cos(q_6) - (sin(q_2) * cos(q_4) - sin(q_4) * cos(q_2) * cos(q_3)) * sin(q_6)) * sin(q_7) + ((sin(q_2) * sin(q_4) + cos(q_2) * cos(q_3) * cos(q_4)) * sin(q_5) + sin(q_3) * cos(q_2) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * (((-sin(q_2) * sin(q_4) - cos(q_2) * cos(q_3) * cos(q_4)) * cos(q_5) + sin(q_3) * sin(q_5) * cos(q_2)) * sin(q_6) + (-sin(q_2) * cos(q_4) + sin(q_4) * cos(q_2) * cos(q_3)) * cos(q_6));
        out_jacobian(2, 2) = -d_ew_ * sin(q_2) * sin(q_3) * sin(q_4) + d_wf_ * ((sin(q_2) * sin(q_3) * cos(q_4) * cos(q_5) + sin(q_2) * sin(q_5) * cos(q_3)) * sin(q_6) - sin(q_2) * sin(q_3) * sin(q_4) * cos(q_6)) + tcp_pos_.x() * (((sin(q_2) * sin(q_3) * cos(q_4) * cos(q_5) + sin(q_2) * sin(q_5) * cos(q_3)) * cos(q_6) + sin(q_2) * sin(q_3) * sin(q_4) * sin(q_6)) * cos(q_7) + (-sin(q_2) * sin(q_3) * sin(q_5) * cos(q_4) + sin(q_2) * cos(q_3) * cos(q_5)) * sin(q_7)) + tcp_pos_.y() * ((-(sin(q_2) * sin(q_3) * cos(q_4) * cos(q_5) + sin(q_2) * sin(q_5) * cos(q_3)) * cos(q_6) - sin(q_2) * sin(q_3) * sin(q_4) * sin(q_6)) * sin(q_7) + (-sin(q_2) * sin(q_3) * sin(q_5) * cos(q_4) + sin(q_2) * cos(q_3) * cos(q_5)) * cos(q_7)) + tcp_pos_.z() * ((sin(q_2) * sin(q_3) * cos(q_4) * cos(q_5) + sin(q_2) * sin(q_5) * cos(q_3)) * sin(q_6) - sin(q_2) * sin(q_3) * sin(q_4) * cos(q_6));
        out_jacobian(2, 3) = d_ew_ * (sin(q_2) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_2)) + d_wf_ * ((sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * sin(q_6) * cos(q_5) + (sin(q_2) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_2)) * cos(q_6)) + tcp_pos_.x() * (((sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * cos(q_5) * cos(q_6) + (-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_6)) * cos(q_7) + (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * sin(q_5) * sin(q_7)) + tcp_pos_.y() * ((-(sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * cos(q_5) * cos(q_6) - (-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_6)) * sin(q_7) + (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * sin(q_5) * cos(q_7)) + tcp_pos_.z() * ((sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * sin(q_6) * cos(q_5) + (sin(q_2) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_2)) * cos(q_6));
        out_jacobian(2, 4) = d_wf_ * (-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * sin(q_6) + tcp_pos_.x() * ((-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * cos(q_6) * cos(q_7) + ((sin(q_2) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_2)) * cos(q_5) - sin(q_2) * sin(q_3) * sin(q_5)) * sin(q_7)) + tcp_pos_.y() * (-(-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * sin(q_7) * cos(q_6) + ((sin(q_2) * cos(q_3) * cos(q_4) - sin(q_4) * cos(q_2)) * cos(q_5) - sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_7)) + tcp_pos_.z() * (-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * sin(q_6);
        out_jacobian(2, 5) = d_wf_ * (((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) - (sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * sin(q_6)) + tcp_pos_.x() * (-((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * sin(q_6) + (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * cos(q_6)) * cos(q_7) + tcp_pos_.y() * (((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * sin(q_6) - (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * cos(q_6)) * sin(q_7) + tcp_pos_.z() * (((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) - (sin(q_2) * sin(q_4) * cos(q_3) + cos(q_2) * cos(q_4)) * sin(q_6));
        out_jacobian(2, 6) = tcp_pos_.x() * (-(((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) + (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * sin(q_6)) * sin(q_7) + (-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * cos(q_7)) + tcp_pos_.y() * ((-((-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * cos(q_5) + sin(q_2) * sin(q_3) * sin(q_5)) * cos(q_6) - (-sin(q_2) * sin(q_4) * cos(q_3) - cos(q_2) * cos(q_4)) * sin(q_6)) * cos(q_7) - (-(-sin(q_2) * cos(q_3) * cos(q_4) + sin(q_4) * cos(q_2)) * sin(q_5) + sin(q_2) * sin(q_3) * cos(q_5)) * sin(q_7));
    }

    void Kinematics::JacobianRot(const Kinematics::JointArrayType &q, Kinematics::JacobianRotType &out_jacobian) {
        T.setIdentity();
        for (int i = 0; i < NUM_OF_JOINTS; ++i) {
            out_jacobian.block<3, 1>(0, i) = T.block<3, 1>(0, 2);
            transform_i(q[i], i, T_tmp);
            T = T * T_tmp;
        }
    }

}