iiwa_front:
  fri_ip: 192.170.10.2
  fri_port: 30202

  conf_ip: 172.31.1.148
  conf_port: 30402

  control_freq: 1000 # in Hz
  joints:
    - F_joint_1
    - F_joint_2
    - F_joint_3
    - F_joint_4
    - F_joint_5
    - F_joint_6
    - F_joint_7

  init_position:
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
  stiffness:
    [200.0, 600.0, 20.0, 400.0, 150, 150, 50]

  damping:
    [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]

iiwa_back:
  fri_app_ip: 192.170.10.1
  fri_app_port: 30201

  fri_conf_ip: 172.31.1.147
  fri_conf_port: 30401

  control_freq: 1000 # in Hz
  joints:
    - B_joint_1
    - B_joint_2
    - B_joint_3
    - B_joint_4
    - B_joint_5
    - B_joint_6
    - B_joint_7

  init_position:
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
  stiffness:
    [200.0, 600.0, 200.0, 400.0, 150.0, 150.0, 50.0]

  damping:
    [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]
