<?xml version="1.0"?>
<robot name="iiwas" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find iiwas_description)/urdf/iiwa14.xacro"/>
    <xacro:include filename="$(find iiwas_description)/urdf/util_defs.xml"/>
    <!-- the mass values and inertia may not be completly correct as the moment so this model should just be used as a kinematic one now-->

    <xacro:property name="M_PI" value="3.1415926535897931"/>
    <xacro:property name="base_height" default="0.03"/>
    <xacro:arg name="hardware_interface" default="PositionJointInterface"/>

    <xacro:include filename="$(find iiwas_description)/urdf/iiwas_frame.urdf.xacro"/>

    <!-- spawn the robot on each of the base-->
    <!-- iiwas front arm -->
    <xacro:iiwa14 parent="front_base" hardware_interface="hardware_interface/$(arg hardware_interface)" robot_name="F">
        <origin xyz="0.0 0.0 ${base_height/2}"
                rpy="0.0 0.0 0.0"/>
    </xacro:iiwa14>

    <!-- iiwas back arm -->
    <xacro:iiwa14 parent="back_base" hardware_interface="hardware_interface/$(arg hardware_interface)" robot_name="B">
        <origin xyz="0.0 0.0 ${base_height/2}"
                rpy="0.0 0.0 ${M_PI}"/>
    </xacro:iiwa14>

    <!-- Load Gazebo lib and set the robot namespace -->
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      </plugin>
    </gazebo>

</robot>
