<?xml version="1.0"?>
<robot name="iiwa" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find iiwas_description)/urdf/materials.xacro" />
  <!--Import the lbr iiwa macro -->
  <xacro:include filename="$(find iiwas_description)/urdf/iiwa14.xacro"/>

  <xacro:property name="base_height" default="0.03"/>
  
  <xacro:arg name="hardware_interface" default="PositionJointInterface"/>
  <xacro:arg name="robot_name" default="F"/>
  <xacro:arg name="parent" default="front_base"/>
  <xacro:arg name="base_rpy" default="0 0 0"/>

  <!-- Fix to world just for testing -->
  <link name="$(arg parent)"/>
  
  <!--iiwa-->
  <xacro:iiwa14 hardware_interface="$(arg hardware_interface)" robot_name="$(arg robot_name)" parent="$(arg parent)">
    <origin xyz="0 0 ${base_height/2}" rpy="$(arg base_rpy)" />
  </xacro:iiwa14>

  <gazebo reference="$(arg parent)">
    <kinematic>true</kinematic>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    </plugin>
  </gazebo>

</robot>
